### ISSUE TITLE
Is it possible to make this work on all responses?

### ISSUE THREAD

**Issue by Mandawi** [technicalpanda/awrence#87]
This other gem [camel patrol](https://github.com/coverhound/camel_patrol) that doesn't work on rails 7 changes all responses from rails to camel case. I'm wondering if it's possible to do that in this gem too. When using libraries that create their own endpoints, it's impossible to just manually camel case the responses so I'm wondering if there's a way to camel case any response.

Any help is appreciated :)

**Comment by schinery** [comment]
Hey @Mandawi, the short answer is no as this gem is just for transforming hashes and doesn't hook into the Rack/Rails middleware. However you do have a couple of options to this if [camel patrol](https://github.com/coverhound/camel_patrol) gem doesn't support Rails 7.

1. Use the [olive branch](https://github.com/vigetlabs/olive_branch) gem 
2. Hack your own version of the [camel patrol middleware](https://github.com/coverhound/camel_patrol/blob/master/lib/camel_patrol/middleware.rb) and use it in your own app

With option 2 you could probably just drop that code into your app and it would "just work" as it is a pretty standard looking Rack middleware setup as long as your app is using Rails. Could remove the less than Rails 5 check too.

Hope this helps.

**Comment by Mandawi** [comment]
Olive branch worked really well for us, thank you!
